# Generated by Django 4.1.5 on 2023-09-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_categories_remove_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
