# Generated by Django 4.1.5 on 2023-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_bookuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='collage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
