# Generated by Django 4.1.5 on 2023-09-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_bookuser_address_alter_bookuser_collage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookuser',
            old_name='collage',
            new_name='college',
        ),
    ]
