# Generated by Django 4.1.5 on 2023-09-03 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_rename_collage_bookuser_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='img/%y')),
                ('book_categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.categories')),
            ],
        ),
    ]
