# Generated by Django 4.1.5 on 2023-09-03 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0009_mybook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='book_categories',
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='title',
        ),
        migrations.AddField(
            model_name='mybook',
            name='book',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='manager.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mybook',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
