# Generated by Django 4.1.5 on 2023-09-03 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_remove_mybook_author_remove_mybook_book_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='user',
        ),
        migrations.AddField(
            model_name='mybook',
            name='book_user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='manager.bookuser'),
            preserve_default=False,
        ),
    ]
